### ISSUE TITLE
Alerts crashes when using overridden config file

### ISSUE THREAD

**Issue by lonnieezell** [tattersoftware/codeigniter4-alerts#12]
Looks like `Alerts.php` expects only the Tatter Alerts config file to be allowed. 

Error encountered: 
```Argument 1 passed to Tatter\Alerts\Alerts::__construct() must be an instance of Tatter\Alerts\Config\Alerts, instance of Config\Alerts given,```

**Comment by MGatner** [comment]
That's correct. If you make your own Config file it should extend the library's version. See **examples/Alerts.php**. 

This library is due for a refresh. If you come across any issues or have a wishlist I'm all ears.

**Comment by lonnieezell** [comment]
That makes sense. I was rushing to add it last night and the docs didn't mention extending the class. I kinda hate to do that since there's only 3 properties but that's an easy switch. Heading on vacation tomorrow so probably won't get to update until I get back. 

At first I didn't see a need for an external library for handling this, since it's a fairly simple thing. But the queue of alerts was what changed my mind. Nice touch!

**Comment by MGatner** [comment]
> Nice touch!

Thanks! I think there is lots of room for improvement, but this was a port from a CI3 module I used heavily, so it was an early library.

> there's only 3 properties

I know it seems a bit overdone, but from a maintainer standpoint it fixes the problem of "what is really in this Config". If I type it to the library's version then I *know those three properties exist*, even if the child class doesn't implement them. It saves a lot of `if (isset($config->foo))` nonsense. It also lets me add properties without requiring a new major version, since developers would not need to update their config files.
